name: QA-UAT-PROD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: './Package'
  DOTNET_VERSION: '5.0.x'
  SLOT_NAME: 'production'
  BRANCH: 'main'

jobs:

  DeployQA:
    name: Deploy to QA
    if: github.event.ref == 'refs/heads/main'
    runs-on: windows-latest
    environment:
      name: QA  
      url: 'https://jefftestgithubactions.azurewebsites.net'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o 'Package'
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: release-github-test
        path: './Package/'
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jefftestgithubactions'
        slot-name: ${{ env.SLOT_NAME }}  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './Package'
          
  DeployUAT:
    name: Deploy to UAT
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployQA]
    runs-on: windows-latest
    environment:
      name: UAT  
      url: 'https://jefftestgithubactionsuat.azurewebsites.net'
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: release-github-test
        path: ./Package
    
    - name: List
      run: |
        ls -R
        ls -R Package
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jefftestgithubactionsuat'
        slot-name: ${{ env.SLOT_NAME }}  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: $(Pipeline.Workspace)/release-github-test
      
  DeployProduction:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployUAT]
    runs-on: windows-latest
    environment:
      name: Production  
      url: 'https://jefftestgithubactionsprod.azurewebsites.net'
    steps:
      - name: 'Deploy to Azure WebApp'
        run: echo Deployed Production     
